code:
    cdn_url: vscode.cdn.azure.cn
    download_url: https://code.visualstudio.com/sha?build=stable
    ext_identifiers:
        - moqsien.easynotes
        - doggy8088.go-extension-pack
        - galkowskit.go-interface-annotations
        - liuchao.go-struct-tag
        - tabnine.tabnine-vscode
        - gruntfuggly.todo-tree
        - zxh404.vscode-proto3
        - premparihar.gotestexplorer
        - ms-python.python
        - ms-python.vscode-pylance
        - donjayamanne.python-environment-manager
        - alefragnani.project-manager
        - yzhang.markdown-all-in-one
        - mhutchie.git-graph
        - asvetliakov.vscode-neovim
        - ms-ceintl.vscode-language-pack-zh-hans
        - bracketpaircolordlw.bracket-pair-color-dlw
        - rust-lang.rust-analyzer
        - vue.volar
        - joe-re.sql-language-server
        - akamud.vscode-theme-onedark
        - pkief.material-icon-theme
    stable_url: az764295.vo.msecnd.net
go:
    compiler_urls:
        - https://golang.google.cn/dl/
        - https://go.dev/dl/
        - https://studygolang.com/dl
    proxies:
        - https://goproxy.cn,direct
        - https://repo.huaweicloud.com/repository/goproxy/,direct
    search_url: https://pkg.go.dev/search?limit=100&m=package&q=%s#more-results
hosts:
    host_filters:
        - github
    max_avg_rtt: 400
    ping_count: 10
    req_timeout: 30
    source_urls:
        - https://www.foul.trade:3000/Johy/Hosts/raw/branch/main/hosts.txt
        - https://gitlab.com/ineo6/hosts/-/raw/master/next-hosts
        - https://raw.hellogithub.com/hosts
    worker_num: 100
nvim:
    checksum_url: https://gitee.com/moqsien/gvc/releases/download/v1/nvim-sha256.txt
    github_proxy: https://ghproxy.com/
    plugins_url: https://gitee.com/moqsien/gvc/releases/download/v1/nvim-plugins.zip
    urls:
        darwin:
            ext: .tar.gz
            name: nvim-macos
            url: https://gitee.com/moqsien/gvc/releases/download/v1/nvim-macos.tar.gz
        linux:
            ext: .tar.gz
            name: nvim-linux64
            url: https://gitee.com/moqsien/gvc/releases/download/v1/nvim-linux64.tar.gz
        windows:
            ext: .zip
            name: nvim-win64
            url: https://gitee.com/moqsien/gvc/releases/download/v1/nvim-win64.zip
